# SIE lens

Using the [lensing gw](https://gpagano.gitlab.io/lensinggw/) package I try to obtain the morse indices of the images for different lens and plot the source, images, caustics, and critical lines.

~ Saif 08/2021

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from gw_lens_dir import lens_model
from lensinggw.amplification_factor.amplification_factor import geometricalOpticsMagnification

In [4]:
default_lens_params = {
    'y0': 8.72665e-11,
    'y1': 0,
    'l0': 0.,
    'l1': 0.,
    'zs': 1.0,
    'zl': 0.5,
    'ml': 5.7e4
}

default_lens_model = lens_model.gwlens_class(default_lens_params)

In [5]:
thetae = default_lens_model.thetaE()
thetae

1.922600673893789e-09

In [11]:
mi = default_lens_model.mi()


---- Solver settings ----

The macromodel analysis will be performed with the following settings:

OnlyMacro         --> True
Scaled            --> False
SearchWindowMacro --> 7.690402695575157e-09
PixelsMacro       --> 1000
PrecisionLimit    --> 1e-20
OverlapDistMacro  --> 1e-15
NearSource        --> False
Optimization      --> False
Verbose           --> False




MACROIMAGES

ra: [ 1.20301369e-18 -1.73603821e-09  1.20301369e-18  1.73603821e-09
 -2.24621246e-20]
dec: [-1.88588354e-09  2.06790065e-24  1.88588354e-09 -1.49826977e-21
  2.02906705e-24]


---- Solver settings ----

The macromodel analysis will be performed with the following settings:

OnlyMacro         --> True
Scaled            --> False
SearchWindowMacro --> 7.690402695575157e-09
PixelsMacro       --> 1000
PrecisionLimit    --> 1e-20
OverlapDistMacro  --> 1e-15
NearSource        --> False
Optimization      --> False
Verbose           --> False




MACROIMAGES

ra: [ 1.20301369e-18 -1.73603821e-09  1.20301369e-18  1.73

In [10]:
mu = default_lens_model.mu()


---- Solver settings ----

The macromodel analysis will be performed with the following settings:

OnlyMacro         --> True
Scaled            --> False
SearchWindowMacro --> 7.690402695575157e-09
PixelsMacro       --> 1000
PrecisionLimit    --> 1e-20
OverlapDistMacro  --> 1e-15
NearSource        --> False
Optimization      --> False
Verbose           --> False




MACROIMAGES

ra: [ 1.20301369e-18 -1.73603821e-09  1.20301369e-18  1.73603821e-09
 -2.24621246e-20]
dec: [-1.88588354e-09  2.06790065e-24  1.88588354e-09 -1.49826977e-21
  2.02906705e-24]


---- Solver settings ----

The macromodel analysis will be performed with the following settings:

OnlyMacro         --> True
Scaled            --> False
SearchWindowMacro --> 7.690402695575157e-09
PixelsMacro       --> 1000
PrecisionLimit    --> 1e-20
OverlapDistMacro  --> 1e-15
NearSource        --> False
Optimization      --> False
Verbose           --> False




MACROIMAGES

ra: [ 1.20301369e-18 -1.73603821e-09  1.20301369e-18  1.73

In [9]:
mu

array([ 7.51660957, -6.21848114,  7.47464196, -6.17349531,  0.02140652])

In [ ]:
img_prop = default_lens_model.lens_model()
img_prop[0] * 206265, img_prop[1] * 20626

In [12]:
tds = default_lens_model.tds() * 1.15741e-5


---- Solver settings ----

The macromodel analysis will be performed with the following settings:

OnlyMacro         --> True
Scaled            --> False
SearchWindowMacro --> 7.690402695575157e-09
PixelsMacro       --> 1000
PrecisionLimit    --> 1e-20
OverlapDistMacro  --> 1e-15
NearSource        --> False
Optimization      --> False
Verbose           --> False




MACROIMAGES

ra: [ 1.20301369e-18 -1.73603821e-09  1.20301369e-18  1.73603821e-09
 -2.24621246e-20]
dec: [-1.88588354e-09  2.06790065e-24  1.88588354e-09 -1.49826977e-21
  2.02906705e-24]


---- Solver settings ----

The macromodel analysis will be performed with the following settings:

OnlyMacro         --> True
Scaled            --> False
SearchWindowMacro --> 7.690402695575157e-09
PixelsMacro       --> 1000
PrecisionLimit    --> 1e-20
OverlapDistMacro  --> 1e-15
NearSource        --> False
Optimization      --> False
Verbose           --> False




MACROIMAGES

ra: [ 1.20301369e-18 -1.73603821e-09  1.20301369e-18  1.73

In [13]:
tds, mu, mi

(array([0.00000000e+00, 1.33977384e-06, 5.13993292e-21, 1.33977383e-06,
        7.03426699e-06]),
 array([ 7.51660957, -6.21848114,  7.47464196, -6.17349531,  0.02140652]),
 [0, 0.5, 0, 0.5, 1])

In [ ]:
default_lens_model.plot_img(plot_name = 'test_plot_sie')

In [ ]:
dummy_frequencies = np.linspace(10,1000,100)
F = geometricalOpticsMagnification(dummy_frequencies,
                                   default_lens_model.lens_model()[0],
                                   default_lens_model.lens_model()[1],
                                   default_lens_model.beta()[0],
                                   default_lens_model.beta()[1],
                                   default_lens_params['zl'],
                                   default_lens_params['zs'],
                                   default_lens_model.lens_model()[-2],
                                   default_lens_model.lens_model()[-1]
                                   )

In [ ]:
plt.plot(dummy_frequencies, np.abs(F))